version: '2'
services:
  web_apache:
    build: .
    ports:
      - "80:80"
    volumes:
      - /Users/leonardollobato/Projects/Foccus:/var/www/site
    depends_on:
      - mysql_test
  mysql_test:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # command:
    #   RUN /bin/bash -c "/usr/bin/mysqld_safe &" && \
    #   sleep 5 && \
    #   mysql -u root -proot -e "CREATE DATABASE acqiodev_payment" && \
    #   mysql -u root -proot mydb < acqiopay_dev.sql